# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('describe', '0007_auto_20141213_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='randomizationmodel',
            old_name='giving',
            new_name='giving_id',
        ),
    ]
