# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 14:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('describe', '0008_auto_20151223_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
